# Generated by Django 3.2.25 on 2025-09-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_auto_20250923_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
