# Generated by Django 3.2.25 on 2025-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_dates',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
