# Generated by Django 3.2.25 on 2025-10-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_dates', '0002_tour_dates_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour_dates',
            options={'ordering': ['date'], 'verbose_name_plural': 'Tour Dates'},
        ),
    ]
